name: group7-front-deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-ssh@release
        env:
          CLONE_DIR: /home/john/node-front-grp7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          command: |
            echo "GRP7 FRONT WORKS"
            git clone -b dev git@github.com:DubocageMatthias/project7-front.git $CLONE_DIR
